{"name": "test_add_int[int3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n +  where 1 = <bound method calculator.add of <pycode.calculator2.calculator.calculator object at 0x0000000003803978>>(1, 0)\n +    where <bound method calculator.add of <pycode.calculator2.calculator.calculator object at 0x0000000003803978>> = <pycode.calculator2.calculator.calculator object at 0x0000000003803978>.add", "trace": "self = <pycode.calculator2.test_cal1.TestCal1 object at 0x0000000003803CC0>, get_data1 = [1, 0, 2], func = <pycode.calculator2.calculator.calculator object at 0x0000000003803978>\n\n    @allure.story(\"整数相加功能\")\n    def test_add_int(self, get_data1, func):\n>       assert func.add(get_data1[0], get_data1[1]) == get_data1[2]\nE       assert 1 == 2\nE        +  where 1 = <bound method calculator.add of <pycode.calculator2.calculator.calculator object at 0x0000000003803978>>(1, 0)\nE        +    where <bound method calculator.add of <pycode.calculator2.calculator.calculator object at 0x0000000003803978>> = <pycode.calculator2.calculator.calculator object at 0x0000000003803978>.add\n\ntest_cal1.py:9: AssertionError"}, "parameters": [{"name": "get_data1", "value": "[1, 0, 2]"}], "start": 1617291884756, "stop": 1617291884757, "uuid": "74f16a17-9d2e-46e0-9dbd-85553b17a38a", "historyId": "1ce68dffb376361cd758c3a160592851", "testCaseId": "b9251f5993548a1df8d2dd6b0ae546fb", "fullName": "test_cal1.TestCal1#test_add_int", "labels": [{"name": "feature", "value": "计算开始"}, {"name": "story", "value": "整数相加功能"}, {"name": "suite", "value": "test_cal1"}, {"name": "subSuite", "value": "TestCal1"}, {"name": "host", "value": "wake-PC"}, {"name": "thread", "value": "18456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal1"}]}